//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Магизин_одежды
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int Id_zakaz { get; set; }
        public int id_tovar { get; set; }
        public System.DateTime Data_zakaza { get; set; }
        public string Sostav { get; set; }
        public decimal Summa { get; set; }
        public int Sum_skidka { get; set; }
        public int Kod_poluchenia { get; set; }
        public int Id_punkt_vidachi { get; set; }
    
        public virtual Punkt_vidachi Punkt_vidachi { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
